version: "3.5"

volumes:
  database_data:
    driver: local

services:
  db:
    image: postgres:latest
    ports:
      - "5433:5432"
    volumes:
      - database_data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  service-dddealer:
    image: service-dddealer
    build: ./
    ports:
      - "50051:50051"
    environment:
      - PORT=50051
      - CONNECTION_STRING=host=db port=5432 user=postgres password=postgres dbname=service_dddealer sslmode=disable
    depends_on:
      - db
    restart: on-failure:5